// <auto-generated />
namespace Sport.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class NameOfYourMigration2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NameOfYourMigration2));
        
        string IMigrationMetadata.Id
        {
            get { return "202311111512548_NameOfYourMigration2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
